// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB5VF7tFrRppLn6phLH-s0TVIJt012Ovc',
    appId: '1:514739717595:web:76386b81095bd8f69e13fe',
    messagingSenderId: '514739717595',
    projectId: 'happycooking-9889a',
    authDomain: 'happycooking-9889a.firebaseapp.com',
    storageBucket: 'happycooking-9889a.appspot.com',
    measurementId: 'G-K4LW1JKV9H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa5KNYt_RJkP6FVZDwxkaCcudYqndEc9Q',
    appId: '1:514739717595:ios:d60e4c49518440499e13fe',
    messagingSenderId: '514739717595',
    projectId: 'happycooking-9889a',
    storageBucket: 'happycooking-9889a.appspot.com',
    iosBundleId: 'com.example.happyCooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB5VF7tFrRppLn6phLH-s0TVIJt012Ovc',
    appId: '1:514739717595:web:60a81a1563fc36689e13fe',
    messagingSenderId: '514739717595',
    projectId: 'happycooking-9889a',
    authDomain: 'happycooking-9889a.firebaseapp.com',
    storageBucket: 'happycooking-9889a.appspot.com',
    measurementId: 'G-CRWR4NX4XP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa5KNYt_RJkP6FVZDwxkaCcudYqndEc9Q',
    appId: '1:514739717595:ios:d60e4c49518440499e13fe',
    messagingSenderId: '514739717595',
    projectId: 'happycooking-9889a',
    storageBucket: 'happycooking-9889a.appspot.com',
    iosBundleId: 'com.example.happyCooking',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcXDUJZM3f5unbVJKmAT9Pmlvsrm6peI',
    appId: '1:514739717595:android:1cbec4f53b9e597d9e13fe',
    messagingSenderId: '514739717595',
    projectId: 'happycooking-9889a',
    storageBucket: 'happycooking-9889a.appspot.com',
  );

}